In [4]:
import pandas as pd
import numpy as np
import os

In [ ]:
dataset_df = pd.read_csv("/home/rifaioglu/projects/GNNClinicalOutcomePrediction/data/Lung/sce_coldata_metadata.csv", sep=",", index_col=0)
counts_df = pd.read_csv('/home/rifaioglu/projects/GNNClinicalOutcomePrediction/data/Lung/sce_counts_matrix.csv', index_col=0)
dataset_df = pd.concat([dataset_df, counts_df], axis=1)
lst_patient_ids = [val.rsplit("_", 1)[0] for val in dataset_df.index]
dataset_df["Sample_ID"] = lst_patient_ids
dataset_df_subset = dataset_df.dropna(subset=['Relapse'])
dataset_df_subset = dataset_df_subset.dropna(subset=['Grade'])
dataset_df_subset["Relapse"] = dataset_df_subset["Relapse"].astype("int")
dataset_df_subset["Grade"] = dataset_df_subset["Grade"].astype("int")
dataset_df_subset.to_csv("/home/rifaioglu/projects/GNNClinicalOutcomePrediction/data/Lung/raw/merged_preprocessed_dataset.csv")

FileNotFoundError: [Errno 2] No such file or directory: '/home/rifaioglu/projects/GNNClinicalOutcomePrediction/data/Lung/filtered_feature_bc_matrix.csv'

In [5]:
dataset_df_subset = pd.read_csv("/home/rifaioglu/projects/GNNClinicalOutcomePrediction/data/Lung/raw/merged_preprocessed_dataset.csv")

/tmp/ipykernel_3737495/2324670756.py:1: DtypeWarning: Columns (56) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset_df_subset = pd.read_csv("/home/rifaioglu/projects/GNNClinicalOutcomePrediction/data/Lung/raw/merged_preprocessed_dataset.csv")


In [1]:
from data_processing import data_processing_lung_pipeline
data_processing_lung_pipeline("/home/rifaioglu/projects/GNNClinicalOutcomePrediction/data/Lung/raw/merged_preprocessed_dataset.csv")

/home/rifaioglu/projects/GNNClinicalOutcomePrediction/bin/data_processing.py:34: DtypeWarning: Columns (56) have mixed types. Specify dtype option on import or set low_memory=False.
  return pd.read_csv(path, index_col=index_col)
100%|██████████| 1878/1878 [06:47<00:00,  4.61it/s]


Calculating cell count distribution....
../data/Lung/raw
Creating graphs...
df_cell_count       Sample_ID  Cell Counts
0      175_A_10         3063
1     175_A_100         3501
2     175_A_102         2655
3     175_A_104         5150
4     175_A_105          875
...         ...          ...
1888    88_C_95         2702
1889    88_C_96         1020
1890    88_C_97         3478
1891    88_C_98         4127
1892    88_C_99         3497

[1878 rows x 2 columns]


  0%|          | 0/1878 [00:04<?, ?it/s]


KeyError: "None of [Index(['Myeloperoxidase (MPO)', 'FSP1 / S100A4', 'SMA', 'Histone H3', 'FAP',\n       'HLA-DR', 'CD146', 'Cadherin-11', 'Carbonic Anhydrase IX',\n       'Collagen I + Fibronectin', 'VCAM1', 'CD20', 'CD68',\n       'Indoleamine 2- 3-dioxygenase (IDO)', 'CD3', 'Podoplanin', 'MMP11',\n       'CD279 (PD-1)', 'CD73', 'MMP9', 'p75 (CD271)', 'TCF1/TCF7', 'CD10',\n       'Vimentin', 'FOXP3', 'CD45RA + CD45R0', 'PNAd', 'CD8a',\n       'CD248 / Endosialin', 'LYVE-1', 'PDGFR-b', 'CD34', 'CD4', 'vWF + CD31',\n       'CXCL12', 'CCL21', 'Pan Cytokeratin + Keratin Epithelial', 'Cadherin-6',\n       'Iridium_191', 'Iridium_193', 'Ki-67', 'Caveolin-1', 'CD15'],\n      dtype='object')] are in the [columns]"

<Figure size 640x480 with 0 Axes>

<Figure size 1920x1440 with 0 Axes>

<Figure size 1920x1440 with 0 Axes>

<Figure size 640x480 with 0 Axes>

In [ ]:
counts = dataset_df_subset_relapse.groupby('Sample_ID')['Relapse'].value_counts().unstack(fill_value=0)
print(sum(counts[0]>0))
print(sum(counts[1]>0))

In [ ]:
counts = dataset_df_subset_grade.groupby('Sample_ID')['Grade'].value_counts().unstack(fill_value=0)
print(sum(counts[1]>0))
print(sum(counts[2]>0))
print(sum(counts[3]>0))

In [ ]:
counts_df = pd.read_csv("/home/rifaioglu/projects/GNNClinicalOutcomePrediction/data/Lung/sce_counts_matrix.csv", sep=",", index_col=0)

In [ ]:
patients_with_stage = dataset_df[dataset_df['Stage'].notna()]['Patient_ID'].nunique()
print(f"Number of unique patients with stage information: {patients_with_stage}")


In [ ]:
dataset_df["Patient_ID"].unique()

In [ ]:
# def create_graphs_delauney_triangulation(data_path, cell_count_thr=CELL_COUNT_THR, GRAPH_DIV_THR=GRAPH_DIV_THR, plot=False, RAW_DATA_PATH = RAW_DATA_PATH, PLOT_PATH=PLOT_PATH):
import os
from data_processing import get_dataset_from_csv, get_cell_count_df, get_edge_length_dist
dataset = "Lung"

RAW_DATA_PATH = os.path.join("../data",dataset,"raw")
OUT_DATA_PATH = os.path.join("../data", "out_data", dataset)
PLOT_PATH = os.path.join("../plots", dataset,"graph_voronoi_plots")

CELL_COUNT_THR = 100
quant= 0.975
df_dataset = get_dataset_from_csv("/home/rifaioglu/projects/GNNClinicalOutcomePrediction/data/Lung/raw/merged_preprocessed_dataset.csv", index_col=0)
# get_edge_length_dist(df_dataset, CELL_COUNT_THR, quant=quant, sample_col="Sample_ID", loc_x="Location_Center_X", loc_y="Location_Center_Y", PLOT_PATH=PLOT_PATH, RAW_DATA_PATH=RAW_DATA_PATH)


In [ ]:
df_dataset[df_dataset["Sample_ID"] == "178_C_107"]["Patient_ID"]

In [ ]:
df_dataset.columns

In [ ]:
df_dataset[["Center_X", "Center_Y"]]

In [ ]:
# get_edge_length_dist(df_dataset, cell_count_thr=CELL_COUNT_THR, quant=quant, sample_col="Sample_ID", loc_x="Center_X", loc_y="Center_Y", PLOT_PATH=PLOT_PATH, RAW_DATA_PATH=RAW_DATA_PATH)

In [ ]:
print("Calculating cell count distribution....")
df_cell_count = get_cell_count_df(df_dataset, CELL_COUNT_THR, sample_col = "Sample_ID")

In [ ]:
df_dataset[["Sample_ID", "Center_X", "Center_Y"]].head(5)

In [ ]:
import numpy as np
quartile = int(np.quantile(df_cell_count["Cell Counts"], 0.50))

In [ ]:
from data_processing import create_graphs_delauney_triangulation    

In [ ]:
create_graphs_delauney_triangulation(df_dataset, cell_count_thr=CELL_COUNT_THR, sample_col= "Sample_ID", pid_col = "Patient_ID",  x_loc ="Center_X", y_loc = "Center_Y", divide_sample=False,  plot=True, RAW_DATA_PATH = RAW_DATA_PATH, PLOT_PATH=PLOT_PATH)

In [ ]:
dataset_df["cell_type"]

In [7]:
from dataset import LungDataset
import os
dataset_name = "Lung"
RAW_DATA_PATH = os.path.join("../data", f"{dataset_name}/raw")
dataset = LungDataset(f"../data/{dataset_name}",  "Relapse")

Seed set to 42
Processing...


Number of samples: 1878
data_list[0] Data(x=[4327, 43], edge_index=[2, 25234], y=[0], pos=[4327, 2], osmonth=273.0, clinical_type='1.0', disease_stage=2.0, tumor_grade=3, img_id='175_A_12_175_49', p_id=49.0, age=83.0, dfs_month=273.0, ct_class=[4327, 2])


Done!


Target prediction: Relapse


In [10]:
import torch

torch.Tensor([0])

tensor([0.])

In [6]:
[data.y for data in list(dataset[:10])]

[tensor([]),
 tensor([7.2439e-41]),
 tensor([]),
 tensor([]),
 tensor([6.9006e-41]),
 tensor([]),
 tensor([]),
 tensor([-1.7255e-10]),
 tensor([]),
 tensor([])]

In [ ]:
for data in dataset:
    print(data, data.y)
    if int(data.y) not in [0, 1]:
        print(f"Data y value is not in [0, 1]: {data.y}")
    

In [ ]:
samplers = custom_tools.k_fold_random_split(dataset)

In [ ]:
import torch
import torch.nn as nn
log_softmax = nn.LogSoftmax(dim=1)
loss_fn = nn.NLLLoss()
# input to NLLLoss is of size N x C = 3 x 5
input = torch.randn(3, 5, requires_grad=True)
# each element in target must have 0 <= value < C
target = torch.tensor([1, 0, 4])
loss = loss_fn(log_softmax(input), target)
loss.backward()

"""# 2D loss example (used, for example, with image inputs)
N, C = 5, 4
loss_fn = nn.NLLLoss()
data = torch.randn(N, 16, 10, 10)
conv = nn.Conv2d(16, C, (3, 3))
log_softmax = nn.LogSoftmax(dim=1)
# output of conv forward is of shape [N, C, 8, 8]
output = log_softmax(conv(data))
# each element in target must have 0 <= value < C
target = torch.empty(N, 8, 8, dtype=torch.long).random_(0, C)
# input to NLLLoss is of size N x C x height (8) x width (8)
loss = loss_fn(output, target)
loss.backward()"""

In [ ]:
target

In [ ]:
log_softmax(input)